### PR TITLE
Layout Improvement, UI Fixing and more

### LINKED ISSUE #14: About us page

### LINKED ISSUE #33: Register Page
https://www.figma.com/file/zy1PqhdxxsICD9168AMY7Y/Dualis-Bot?node-id=8%3A2

### PR DESCRIPTION
**Pull request by steffenhls**
Closes #14 
Closes #33 

- improved layout for mobile screens
- changed ui
- added footer
- added tab icon
- added dialogs and improved disabled buttons
- ...

### CODE REVIEW

File: frontend/src/routes/About.svelte [hunk 1]
```diff
@@ -19,66 +20,70 @@
 		for (let index = 0; index < person.length; index++) {
             if (person[index].id == id){
                 person[index].opacity = 0.5;
```
Comment (MaikKBRNK) [inline frontend/src/routes/About.svelte:22]: Very nice. Thanks for the fix.

File: frontend/src/routes/Register.svelte [hunk 2]
```diff
@@ -59,222 +55,200 @@
...
+                            <input class="input" placeholder="Benutzername" bind:value={username}/>
+                            <input class="input" placeholder="Passwort" type="password" bind:value={password}/>
+                            <input class="input" placeholder="Passwort (wiederholen)" type="password" bind:value={passwordRepeat}/>
+                            {#if password != passwordRepeat}
+                                <p class="warning">
+                                    Die Passwörter stimmen nicht überein!
+                                </p>
+                            {/if}
+                            <div style="text-align: right">
+                                <button class="rButton" id="buttonNext1" disabled={password!=passwordRepeat || !username || !password} on:click={nextStep}>
```
Comment (MaikKBRNK) [inline frontend/src/routes/Register.svelte:93]: Very smart.

File: frontend/src/routes/Register.svelte [hunk 3]
```diff
@@ -59,222 +55,200 @@
...
+                    </SvelteStepWizard.Step>
+                    <SvelteStepWizard.Step num={2} let:previousStep let:nextStep>
+                        <div>
+                            <h1>Telegram</h1>
+                            <hr/>
+                            <p>
+                                Für eine Telegram Benachrichtigung musst du hier deine Chat ID eingeben.
+                            </p>
+                            <button class="gButton" style="margin-top: -5px; margin-bottom: 15px;" on:click={() => (telegramDialog = true)}>
+                                <img class="infoPic" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Infobox_info_icon.svg/1200px-Infobox_info_icon.svg.png" alt="infoIcon" height="20px" />
```
Comment (MaikKBRNK) [inline frontend/src/routes/Register.svelte:107]: There is now the icon available under "https://dualis-crawler.s3.eu-central-1.amazonaws.com/icon.png"
